### ISSUE TITLE
header image

### ISSUE THREAD

**Issue by maman** [Atriedes/mabes#20]
tolong header image yg di dentya, tak pasang sekalian

**Comment by Atriedes** [comment]
woke, ukuran brp?

**Comment by maman** [comment]
wes titip kemarin, tinggal ambil tok.

**Comment by Atriedes** [comment]
main banner:
![mainbanner](https://cloud.githubusercontent.com/assets/603125/5780076/3800eb78-9dda-11e4-90e8-9aff4fc2a78b.jpg)

deposit:
![deposit](https://cloud.githubusercontent.com/assets/603125/5780080/419b603c-9dda-11e4-95e4-8f62983e168a.jpg)

finance operation:
![finoperation](https://cloud.githubusercontent.com/assets/603125/5780084/43b29142-9dda-11e4-8196-65483f6dee51.jpg)

rebates:
![rebates](https://cloud.githubusercontent.com/assets/603125/5780087/486fb142-9dda-11e4-8985-67a79f0971f0.jpg)

transfer balance:
![transbalance](https://cloud.githubusercontent.com/assets/603125/5780089/4d134682-9dda-11e4-8ff4-c7543faf7560.jpg)

transfer status:
![transstat](https://cloud.githubusercontent.com/assets/603125/5780096/55e69a70-9dda-11e4-81df-e3607203db4b.jpg)

withdrawal:
![withdrawal](https://cloud.githubusercontent.com/assets/603125/5780098/5b011224-9dda-11e4-9bb2-bbe605e5dd05.jpg)
